#!/bin/bash

# Source Files
# $BIOINFX/bin expected to be defined.
# source "$BIOINFX/bin/archiveRunFolder"
# source "$BIOINFX/bin/archiveSASRunFolder"

if [ "$#" != "3" ]
then
  echo ''
  echo 'Archives the specified SAS NGS run folder to the specified location, wraped for ES.'
  echo 'The run folder is deleted from its original location after archiving.'
  echo 'The archived run folder location is logged to'
  echo "$BIOINFX/ngs/stats/Archive.log"
  echo 'for each accession specified in the accessions panels file.'
  echo "Edward Tan, version 1.0, 2018-4-23"
  echo ''
  echo 'Dependencies - Source Files'
  echo '$BIOINFX/bin/archiveRunFolder'
  echo '$BIOINFX/bin/archiveSASRunFolder'
  echo ''
  echo 'Arguments:'
  echo '1. Workfkow.'
  echo '2. Run folder path.'
  echo '3. Archive folder path (the run folder will be created within this folder).'
  echo ''
  echo 'Example Usage: archiveRunFolder AccessionsPanels.txt /path/to/run/folder /path/to/archive/folder ngsRun'
  echo ''
  exit 1
fi

if [ $1 == "completeRunSS" || $1 == "somRun" || $1 == "completeRunRD" ]
then
  $BIOINFX/bin/archiveSASRunFolder "SAS" $2 $3 || exit 1
else
  cat $(ls AccessionsPanels*.txt | grep -v "_" | grep -v "AccessionsPanelsPoolIDs.txt") > $2/AccessionPanels.txt || { echo "*** ERROR ***: Failed to merge accession panel files in $2"; exit 1; }
  $BIOINFX/bin/archiveRunFolder $2/AccessionPanels.txt $2 $3 || exit 1
fi

exit 0;